### ISSUE TITLE
HolograpicDisplay

### ISSUE THREAD

**Issue by martijnpu** [aBo0oDyy/RelCon-Expansion#2]
Hey,

When I try to use this Expansion it just don't activate. I use the following:
`%rel_relcon_viewer_tooltip.staff_&8&lVisible_&8&lUnvisible%`

This is what I get. I installed relcon and reloaded Papi already.
![image](https://user-images.githubusercontent.com/38832167/62560815-23f29000-b87e-11e9-904e-f5ebc305806d.png)

martijnpu

**Comment by aBooDyy** [comment]
Hey there,
Holographic Displays plugin doesn't support PlaceholderAPI by itself, you'll have to download [Holographic Extension](https://www.spigotmc.org/resources/holographicextension.18461/) plugin (And don't forget to download it's dependency [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/)) to be able to use PAPI placeholders in Holographic Displays plugin.

Also, keep in mind that not all plugins support relation placeholders, i don't know if Holographic Extension does so not sure if RelCon expansion will work there because it's placeholders are relational placeholders.

Let me know if it worked.

**Comment by aBooDyy** [comment]
Closed due to no reply.
